"""Add base specifications table

Revision ID: 82fe994027e8
Revises: ae875ab49192
Create Date: 2025-12-07 10:13:14.175579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe994027e8'
down_revision: Union[str, Sequence[str], None] = 'ae875ab49192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_displacement', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'electric', 'hybrid', 'lpg', name='fueltypeenum'), nullable=False),
    sa.Column('horsepower', sa.Integer(), nullable=True),
    sa.Column('torque', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('drivetrain', sa.String(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('zero_to_100', sa.Float(), nullable=True),
    sa.Column('top_speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_name'), 'generations', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_name'), table_name='generations')
    op.drop_table('base_specs')
    # ### end Alembic commands ###
