"""Add on delete for all tables

Revision ID: 86e16b832a0a
Revises: 82fe994027e8
Create Date: 2025-12-07 15:04:18.116363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e16b832a0a'
down_revision: Union[str, Sequence[str], None] = '82fe994027e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('base_specs_generation_id_fkey'), 'base_specs', type_='foreignkey')
    op.create_foreign_key(None, 'base_specs', 'generations', ['generation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('generations_submodel_id_fkey'), 'generations', type_='foreignkey')
    op.create_foreign_key(None, 'generations', 'submodels', ['submodel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('models_brand_id_fkey'), 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('submodels_model_id_fkey'), 'submodels', type_='foreignkey')
    op.create_foreign_key(None, 'submodels', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submodels', type_='foreignkey')
    op.create_foreign_key(op.f('submodels_model_id_fkey'), 'submodels', 'models', ['model_id'], ['id'])
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key(op.f('models_brand_id_fkey'), 'models', 'brands', ['brand_id'], ['id'])
    op.drop_constraint(None, 'generations', type_='foreignkey')
    op.create_foreign_key(op.f('generations_submodel_id_fkey'), 'generations', 'submodels', ['submodel_id'], ['id'])
    op.drop_constraint(None, 'base_specs', type_='foreignkey')
    op.create_foreign_key(op.f('base_specs_generation_id_fkey'), 'base_specs', 'generations', ['generation_id'], ['id'])
    # ### end Alembic commands ###
